/**
 * Reads plugin/ directory and generates src/cli/plugin-files.ts
 * with all file contents embedded as string constants.
 *
 * Run: bun scripts/generate-plugin-embed.ts
 * Run before: bun build --compile
 */

import {
  readdirSync, readFileSync, statSync, writeFileSync,
} from "fs";
import { join, relative } from "path";
import { fileURLToPath } from "url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const PLUGIN_DIR = join(__dirname, "..", "plugin");
const OUT_FILE = join(__dirname, "..", "src", "cli", "plugin-files.ts");

interface ToolFiles {
  [relativePath: string]: string;
}

interface PluginBundle {
  [tool: string]: ToolFiles;
}

function collectFiles(dir: string, base: string): [string, string][] {
  const results: [string, string][] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const rel = relative(base, full).replace(/\\/g, "/");
    if (statSync(full).isDirectory()) {
      results.push(...collectFiles(full, base));
    } else {
      results.push([rel, readFileSync(full, "utf-8")]);
    }
  }
  return results;
}

// Collect all canonical plugin files
const pluginFiles: [string, string][] = [];
const pluginDirs = ["skills", "hooks", "references", "scripts", ".claude-plugin"];
for (const dir of pluginDirs) {
  const dirPath = join(PLUGIN_DIR, dir);
  try {
    pluginFiles.push(...collectFiles(dirPath, PLUGIN_DIR));
  } catch {
    // dir may not exist
  }
}

// --- Claude Code: gets the entire plugin as-is ---
const claudeFiles: ToolFiles = {};
for (const [rel, content] of pluginFiles) {
  claudeFiles[rel] = content;
}

// --- OpenCode: skills → .opencode/skills/kolshek-{name}/ ---
const opencodeFiles: ToolFiles = {};
const skillsDir = join(PLUGIN_DIR, "skills");
try {
  for (const skillName of readdirSync(skillsDir)) {
    const skillDir = join(skillsDir, skillName);
    if (!statSync(skillDir).isDirectory()) continue;
    for (const [rel, content] of collectFiles(skillDir, skillDir)) {
      opencodeFiles[`skills/kolshek-${skillName}/${rel}`] = content;
    }
    // Inject cli-reference.md into each skill's references/
    try {
      const cliRef = readFileSync(join(PLUGIN_DIR, "references", "cli-reference.md"), "utf-8");
      opencodeFiles[`skills/kolshek-${skillName}/references/cli-reference.md`] = cliRef;
    } catch {}
  }
} catch {}

// --- Codex: skills → ~/.codex/skills/kolshek-{name}/ ---
const codexFiles: ToolFiles = {};
try {
  for (const skillName of readdirSync(skillsDir)) {
    const skillDir = join(skillsDir, skillName);
    if (!statSync(skillDir).isDirectory()) continue;
    for (const [rel, content] of collectFiles(skillDir, skillDir)) {
      codexFiles[`kolshek-${skillName}/${rel}`] = content;
    }
    // Inject cli-reference.md
    try {
      const cliRef = readFileSync(join(PLUGIN_DIR, "references", "cli-reference.md"), "utf-8");
      codexFiles[`kolshek-${skillName}/references/cli-reference.md`] = cliRef;
    } catch {}
  }
} catch {}

// --- OpenClaw: skills → ~/.openclaw/workspace/skills/kolshek-{name}/ ---
// Same file layout as Codex (SKILL.md + references/), different install destination
const openclawFiles: ToolFiles = { ...codexFiles };

// Build the bundle
const bundle: PluginBundle = {
  "claude-code": claudeFiles,
  "opencode": opencodeFiles,
  "codex": codexFiles,
  "openclaw": openclawFiles,
};

// Generate TypeScript
const lines: string[] = [
  "// AUTO-GENERATED by scripts/generate-plugin-embed.ts — do not edit",
  "// Embeds plugin files so they survive bun build --compile.",
  "",
  "export interface PluginBundle {",
  "  [tool: string]: { [path: string]: string };",
  "}",
  "",
  "export const PLUGIN_FILES: PluginBundle = {",
];

for (const [tool, files] of Object.entries(bundle)) {
  lines.push(`  ${JSON.stringify(tool)}: {`);
  for (const [path, content] of Object.entries(files)) {
    lines.push(`    ${JSON.stringify(path)}: ${JSON.stringify(content)},`);
  }
  lines.push("  },");
}

lines.push("};");
lines.push("");

writeFileSync(OUT_FILE, lines.join("\n"));

const toolCount = Object.keys(bundle).length;
const fileCount = Object.values(bundle).reduce((sum, files) => sum + Object.keys(files).length, 0);
console.log(`Generated ${OUT_FILE}`);
console.log(`  ${toolCount} tools, ${fileCount} files embedded`);
