// Reads src/web/dist/app/ and assets/ and generates src/web/web-files.ts
// with all SPA + static assets embedded as base64 (binary) or utf-8 (text).
//
// Run: bun scripts/generate-web-embed.ts
// Run after: bun run build:web
// Run before: bun build --compile

import {
  readdirSync, readFileSync, statSync, writeFileSync,
} from "fs";
import { join, relative, extname } from "path";
import { fileURLToPath } from "url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const ROOT = join(__dirname, "..");
const SPA_DIR = join(ROOT, "src", "web", "dist", "app");
const ASSETS_DIR = join(ROOT, "assets");
const OUT_FILE = join(ROOT, "src", "web", "web-files.ts");

// Extensions that should be stored as base64 (binary files)
const BINARY_EXTS = new Set([".png", ".jpg", ".jpeg", ".gif", ".ico", ".woff", ".woff2", ".webp", ".avif"]);

interface EmbeddedFile {
  content: string;
  binary: boolean;
  mime: string;
}

const MIME_MAP: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".webp": "image/webp",
};

function getMime(filePath: string): string {
  return MIME_MAP[extname(filePath).toLowerCase()] || "application/octet-stream";
}

function collectDir(dir: string, base: string): [string, EmbeddedFile][] {
  const results: [string, EmbeddedFile][] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      results.push(...collectDir(full, base));
    } else {
      const rel = "/" + relative(base, full).replace(/\\/g, "/");
      const ext = extname(full).toLowerCase();
      const binary = BINARY_EXTS.has(ext);
      const content = binary
        ? readFileSync(full).toString("base64")
        : readFileSync(full, "utf-8");
      results.push([rel, { content, binary, mime: getMime(full) }]);
    }
  }
  return results;
}

// Collect SPA build output
const files = new Map<string, EmbeddedFile>();

try {
  for (const [path, file] of collectDir(SPA_DIR, SPA_DIR)) {
    files.set(path, file);
  }
} catch (e) {
  console.error("ERROR: SPA dist not found at", SPA_DIR);
  console.error("Run 'bun run build:web' first.");
  process.exit(1);
}

// Collect static assets (logo.png, favicon.png)
try {
  for (const name of ["logo.png", "favicon.png"]) {
    const full = join(ASSETS_DIR, name);
    if (statSync(full).isFile()) {
      const content = readFileSync(full).toString("base64");
      files.set("/" + name, { content, binary: true, mime: "image/png" });
    }
  }
} catch {}

// Generate TypeScript
const lines: string[] = [
  "// AUTO-GENERATED by scripts/generate-web-embed.ts — do not edit",
  "// Embeds SPA build output + static assets so they survive bun build --compile.",
  "",
  "export interface EmbeddedAsset {",
  "  content: string;",
  "  binary: boolean;",
  "  mime: string;",
  "}",
  "",
  "export const WEB_FILES: Record<string, EmbeddedAsset> = {",
];

for (const [path, file] of files) {
  lines.push(`  ${JSON.stringify(path)}: { content: ${JSON.stringify(file.content)}, binary: ${file.binary}, mime: ${JSON.stringify(file.mime)} },`);
}

lines.push("};");
lines.push("");

writeFileSync(OUT_FILE, lines.join("\n"));

const textCount = [...files.values()].filter((f) => !f.binary).length;
const binaryCount = [...files.values()].filter((f) => f.binary).length;
const totalKB = Math.round([...files.values()].reduce((sum, f) => sum + f.content.length, 0) / 1024);
console.log(`Generated ${OUT_FILE}`);
console.log(`  ${files.size} files embedded (${textCount} text, ${binaryCount} binary, ~${totalKB} KB)`);
